name: slang_example
description: Example project using slang.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animated_toggle_switch:
  flutter:
    sdk: flutter
  locale_switcher:
    path: ../../
  slang: ^3.16.0 # add this
  slang_flutter: ^3.16.0 # add this
  flutter_localizations: # add this
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
#  build_runner: any
#  slang_build_runner: any

flutter:
  uses-material-design: true