# An example of l10n.yaml 
arb-dir: example/lib/src/l10n
template-arb-file: intl_en.arb
output-dir: example/lib/src/l10n/generated
output-localization-file: app_localizations.dart
untranslated-messages-file: desiredFileName.txt
preferred-supported-locales: ["en", "vi", "de"]
nullable-getter: false