name: locale_switcher_dev
description: A minimalistic widget for switching the locale of your application with 4 lines of code.
repository: https://github.com/Alexqwesa/locale_switcher/tree/builder
homepage: https://github.com/Alexqwesa/locale_switcher/tree/builder
#author: Alexqwesa <alexo.veto@gmail.com>

version: 0.12.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  build: ^2.4.1
  build_config: ^1.1.1
  build_runner: ^2.4.6
  flutter:
    sdk: flutter
  path: ^1.8.3
  yaml: ^3.1.2

dev_dependencies: # for tests and examples
  animated_toggle_switch:
  easy_localization:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_localizations: #
    sdk: flutter
  flutter_svg: ^2.0.7
#  locale_switcher:
#    path: lib/src/locale_switcher
  intl:
  shared_preferences: ^2.2.1


# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
