name: locale_switcher
description: A widget for switching the locale of your application with 2 lines of code.
repository: https://github.com/Alexqwesa/locale_switcher
homepage: https://github.com/Alexqwesa/locale_switcher
#author: Alexqwesa <alexo.veto@gmail.com>

version: 0.9.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animated_toggle_switch: ^0.8.0
  circle_flags: ^3.0.1
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #  build_runner:
  flutter_lints: ^2.0.0
  flutter_localizations:
    sdk: flutter
  intl:
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
