name: locale_switcher
description: A widget for switching the locale of your application with 2 lines of code.
repository: https://github.com/Alexqwesa/locale_switcher
homepage: https://github.com/Alexqwesa/locale_switcher
#author: Alexqwesa <alexo.veto@gmail.com>

version: 1.3.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter_svg: ^2.0.10+1
  flutter:
    sdk: flutter
  shared_preferences:

dev_dependencies: # for tests and examples
  animated_toggle_switch:
  build:
  build_config:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_localizations:
    sdk: flutter
  intl:
  easy_localization:
  slang:
  url_launcher:

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
